
server:
  port: 8761

eureka:
  instance:
    hostname: https://discoveryservice-1.onrender.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  profiles:
    active: default

management:
  endpoints:
    web:
      exposure:
        include: '*'
