server:
  port: 8761

eureka:
  instance:
    hostname: discoveryservice-1.onrender.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://discoveryservice-1.onrender.com:8761/eureka/

spring:
  profiles:
    active: default

management:
  endpoints:
    web:
      exposure:
        include: '*'
